### ISSUE TITLE
Configurable readiness and liveness

### ISSUE THREAD

**Issue by corkupine** [moov-io/charts#32]
We've been experiencing issues with Watchman pods restarting. Based on [this issue](https://github.com/moov-io/watchman/issues/214), it looks like we're not alone. We'd like to be able to make aspects of the readiness probe and liveness probe configurable.

**Comment by adamdecaf** [comment]
I've merged the PR and in a second commit updated the chart/image versions. Does this work for you to upgrade and use the new attributes?
